language: php
sudo: required
before_script:
  - composer require mikehaertl/phpwkhtmltopdf
script:
  - vendor/mikehaertl/phpwkhtmltopdf
install:
  - php wkhtmltopdf.php
artifacts:
  paths:
  - MatthieuBorgognonCV.pdf
only:
  - master
