language: php
sudo: required
script:
  - mkdir _build
  - php wkhtmltopdf.php
deploy:
  provider: releases
  api_key:
    secure: LAYP_a5qSU7ItrqBfFwm6w
  file:
    - _build/MatthieuBorgognonCV.pdf
  skip_cleanup: true
  on:
    tags: true
only:
  - master
